name: Dynamic Document Deployment

on:
  push:
    paths:
      - '**/*.typ'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Docs Repo
        uses: actions/checkout@v4

      - name: Install Typst
        run: |
          curl -L https://github.com/typst/typst/releases/download/v0.11.0/typst-x86_64-unknown-linux-musl.tar.xz | tar xJ
          echo "$(pwd)/typst-x86_64-unknown-linux-musl" >> $GITHUB_PATH

      - name: Compile All Documents
        run: |
          # Compile all .typ files while preserving folder structure
          find . -name '*.typ' | while read typ_file; do
            rel_path="${typ_file#./}"
            pdf_path="${rel_path%.typ}.pdf"
            mkdir -p "compiled/$(dirname "$pdf_path")"
            typst compile "$typ_file" "compiled/$pdf_path"
          done

      - name: Deploy to Site Repo
        env:
          GITHUB_TOKEN: ${{ secrets.SITE_REPO_TOKEN }}
        run: |
          git clone "https://oauth2:$GITHUB_TOKEN@github.com/your-username/site-repo.git"
          cd site-repo
          
          # Remove old files and copy new ones
          rm -rf [0-9]-*
          cp -r ../compiled/* .
          
          # Generate updated index.html
          cp index.html ..
          cd ..
          python3 generate_html.py
          cp index.html site-repo/
          
          # Commit changes
          cd site-repo
          git add .
          git commit -m "Update documents: $(date +'%Y-%m-%d')"
          git push origin main
